% runAssignment05_Group01
% Group 01, AY2025-2026

clc; clear; close all
format long

projectRoot = fileparts(which('runAssignment05_Group01.m'));
addpath(genpath(projectRoot));

%% Exercise 1a - Curve bootstrap and LMM calibration

results1a = runExercise1a( ...
    'MktData_CurveBootstrap.xls', ...
    'dd-mmm-yy');

curveDatesSet = results1a.curveDatesSet;
curveRatesSet = results1a.curveRatesSet;

marketBaseLmm = results1a.marketBaseLmm;
productContract = results1a.productContract;
productBase = results1a.productBase;
volsLmmBase = results1a.volsLmmBase;

%% Exercise 1b and 1g - Fair upfront and digital smile risk

results1b = runExercise1bg( ...
    marketBaseLmm, ...
    productBase, ...
    productContract, ...
    volsLmmBase);

upfrontCorrected = results1b.upfrontCorrected;
upfrontUncorrected = results1b.upfrontUncorrected;

%% Pricing convention used for risk measures
useSmileCorrectionForRisk = false;

if useSmileCorrectionForRisk
    upfrontForRisk = upfrontCorrected;
else
    upfrontForRisk = upfrontUncorrected;
end

%% Exercise 1c - Parallel and Bucket DV01
resultsExercise1c = runExercise1c( ...
    curveDatesSet, ...
    curveRatesSet, ...
    volsLmmBase, ...
    marketBaseLmm, ...
    productBase, ...
    productContract, ...
    upfrontForRisk, ...
    useSmileCorrectionForRisk);

%% Exercise 1d - Total Vega
results1d = runExercise1d( ...
    marketBaseLmm, ...
    productBase, ...
    upfrontForRisk, ...
    useSmileCorrectionForRisk);

%% Exercise 1e - Coarse-Grained Bucket Hedge
results1e = runExercise1e( ...
    curveDatesSet, ...
    curveRatesSet, ...
    marketBaseLmm, ...
    productBase, ...
    productContract, ...
    volsLmmBase, ...
    upfrontForRisk, ...
    useSmileCorrectionForRisk);

%% Exercise 1f - Coarse-Grained Vega Bucket Hedge

results1f = runExercise1f( ...
    marketBaseLmm, ...
    productBase, ...
    volsLmmBase, ...
    upfrontForRisk, ...
    useSmileCorrectionForRisk);


%% Exercise 2 - Exotic Cap in BMM
results2 = runExercise2( ...
    marketBaseLmm);