function results = computeDV01Parallel( ...
    datesUp, discountsUp, zeroRatesUp, ...
    volsLMMBase, marketBase, ...
    productBase, productContract, ...
    upfront, useSmileCorrection)
%COMPUTEDV01PARALLEL Compute partial and total parallel DV01.
%
%   results = computeDV01Parallel( ...
%       datesUp, discountsUp, zeroRatesUp, ...
%       volsLMMBase, marketBase, ...
%       productBase, productContract, ...
%       upfront, useSmileCorrection)
%
%   computes the mark-to-market change generated by a parallel shocked
%   curve.
%
%   Two measures are reported:
%
%       partialDV01
%           Curve-only effect. The shocked curve is used for discounting and
%           forward rates, while the base calibrated LMM volatilities are
%           kept fixed.
%
%       totalDV01
%           Curve-plus-recalibration effect. The shocked curve is used and
%           the LMM volatility matrix is recalibrated on the shocked market.
%
%   The reference date is assumed to be unchanged by the parallel shock.
%   Therefore the base LMM volatility matrix remains aligned with the
%   shocked tenor reset-time grid for the partial calculation.
%
%   INPUTS:
%       datesUp
%           Bootstrapped curve dates after the parallel shock.
%
%       discountsUp
%           Bootstrapped discount factors after the parallel shock.
%
%       zeroRatesUp
%           Bootstrapped zero rates after the parallel shock.
%
%       volsLMMBase
%           Base calibrated LMM volatility matrix in decimal units. Rows are
%           aligned with marketBase.tenor.resetTimes(2:end).
%
%       marketBase
%           Base market struct.
%
%       productBase
%           Product struct already prepared on marketBase.
%
%       productContract
%           Contractual product struct, not yet prepared on the shocked
%           market.
%
%       upfront
%           Upfront percentage used in the selected pricing convention. If
%           omitted or empty, zero is used.
%
%       useSmileCorrection
%           Pricing convention selector:
%
%               true
%                   Use smile-corrected Party B pricing.
%
%               false
%                   Use uncorrected Black-76 Party B pricing.
%
%           If omitted or empty, true is used.
%
%   OUTPUT:
%       results
%           Struct containing base MtM, shocked MtMs, partial and total
%           mark-to-market changes, recalibrated volatilities and volatility
%           diagnostics.
%
%   NOTE:
%       partialDV01 and totalDV01 are raw MtM differences in EUR for the
%       shock already embedded in datesUp, discountsUp and zeroRatesUp. If
%       the shocked curve corresponds to a +1 bp parallel shift, then these
%       quantities are EUR/bp.

    if nargin < 8 || isempty(upfront)
        upfront = 0.0;
    end

    if nargin < 9 || isempty(useSmileCorrection)
        useSmileCorrection = true;
    end

    %% Base scenario

    [mtmBaseCorrected, mtmBaseUncorrected] = computeMtm( ...
        marketBase, ...
        productBase, ...
        volsLMMBase, ...
        upfront, ...
        upfront);

    mtmBase = selectMtM( ...
        mtmBaseCorrected, ...
        mtmBaseUncorrected, ...
        useSmileCorrection);

    %% Shocked market

    marketUp = initializeInterestRateMarket( ...
        datesUp, ...
        discountsUp, ...
        zeroRatesUp);

    productUp = prepareProductForPricing( ...
        productContract, ...
        marketUp);

    %% Partial DV01: shocked curve, base LMM vols

    [partialMtmUpCorrected, partialMtmUpUncorrected] = computeMtm( ...
        marketUp, ...
        productUp, ...
        volsLMMBase, ...
        upfront, ...
        upfront);

    partialMtmUp = selectMtM( ...
        partialMtmUpCorrected, ...
        partialMtmUpUncorrected, ...
        useSmileCorrection);

    partialDV01 = partialMtmUp - mtmBase;

    %% Total DV01: shocked curve, recalibrated LMM vols

    volsLMMUp = calibrateLMM(marketUp);

    [totalMtmUpCorrected, totalMtmUpUncorrected] = computeMtm( ...
        marketUp, ...
        productUp, ...
        volsLMMUp, ...
        upfront, ...
        upfront);

    totalMtmUp = selectMtM( ...
        totalMtmUpCorrected, ...
        totalMtmUpUncorrected, ...
        useSmileCorrection);

    totalDV01 = totalMtmUp - mtmBase;

    %% Store results

    results = struct();

    results.useSmileCorrection = useSmileCorrection;
    results.pricingLabel = getPricingLabel(useSmileCorrection);

    results.upfront = upfront;
    results.upfrontAmount = upfront * productContract.principal;

    results.mtmBase = mtmBase;
    results.partialMtmUp = partialMtmUp;
    results.totalMtmUp = totalMtmUp;

    results.partialDV01 = partialDV01;
    results.totalDV01 = totalDV01;
    results.diff = totalDV01 - partialDV01;

    results.marketUp = marketUp;
    results.productUp = productUp;

    results.volsLMMBase = volsLMMBase;
    results.volsLMMUp = volsLMMUp;

    results.volDiff = volsLMMUp - volsLMMBase;
    results.maxAbsVolDiff = max(abs(results.volDiff), [], 'all');

end