function vegaMatrix = computeCapVegaMatrix( ...
    market, volsLmm6yUp, volsLmm6yDown, ...
    volsLmm10yUp, volsLmm10yDown, capStrikes, ...
    bumpVol, reportedVolShift)
%COMPUTECAPVEGAMATRIX Compute cap hedge Vega matrix.
%
%   vegaMatrix = computeCapVegaMatrix( ...
%       market, volsLmm6yUp, volsLmm6yDown, ...
%       volsLmm10yUp, volsLmm10yDown, capStrikes, ...
%       bumpVol, reportedVolShift)
%
%   computes the 2 x 2 Vega matrix of the hedge caps.
%
%   Rows correspond to Vega buckets:
%
%       row 1: 0y-6y bucket
%       row 2: 6y-10y bucket
%
%   Columns correspond to hedge caps:
%
%       col 1: 6y cap
%       col 2: 10y cap
%
%   INPUTS:
%       market
%           Base market struct.
%
%       volsLmm6yUp, volsLmm6yDown
%           LMM volatilities calibrated after up/down 0y-6y Vega bucket
%           shocks.
%
%       volsLmm10yUp, volsLmm10yDown
%           LMM volatilities calibrated after up/down 6y-10y Vega bucket
%           shocks.
%
%       capStrikes
%           Column vector [2 x 1] containing ATM strikes for the 6y and 10y
%           hedge caps.
%
%       bumpVol
%           Technical volatility bump used in finite difference.
%
%       reportedVolShift
%           Volatility shift used for reporting, e.g. 0.01 for 1%.
%
%   OUTPUT:
%       vegaMatrix
%           Matrix [2 x 2] of cap bucket Vegas.

    strike6y = capStrikes(1);
    strike10y = capStrikes(2);

    vegaCap6y6y = computeCapVegaFromBumpedVols( ...
        market, ...
        volsLmm6yUp, ...
        volsLmm6yDown, ...
        strike6y, ...
        6, ...
        bumpVol, ...
        reportedVolShift);

    vegaCap6y10y = computeCapVegaFromBumpedVols( ...
        market, ...
        volsLmm10yUp, ...
        volsLmm10yDown, ...
        strike6y, ...
        6, ...
        bumpVol, ...
        reportedVolShift);

    vegaCap10y6y = computeCapVegaFromBumpedVols( ...
        market, ...
        volsLmm6yUp, ...
        volsLmm6yDown, ...
        strike10y, ...
        10, ...
        bumpVol, ...
        reportedVolShift);

    vegaCap10y10y = computeCapVegaFromBumpedVols( ...
        market, ...
        volsLmm10yUp, ...
        volsLmm10yDown, ...
        strike10y, ...
        10, ...
        bumpVol, ...
        reportedVolShift);

    vegaMatrix = [
        vegaCap6y6y,  vegaCap10y6y
        vegaCap6y10y, vegaCap10y10y
    ];

end