function diagnosticsExoticCapSpotCoupons(product, stats)
%DIAGNOSTICSEXOTICCAPSPOTCOUPONS Print per-coupon spot MC diagnostics.

    fprintf('============================================================\n');
    fprintf(' Spot MC coupon diagnostics\n');
    fprintf('============================================================\n');
    fprintf('%5s %8s %8s %8s %18s %18s %18s %18s\n', ...
        'Cpn', 'PrevIdx', 'CurrIdx', 'PayIdx', ...
        'MeanPayoff', 'MeanDisc', 'Contribution', 'DiscError');

    for c = 1:stats.nCoupons

        fprintf('%5d %8d %8d %8d %18.10f %18.10f %18.10f %18.10e\n', ...
            c, ...
            product.previousStartIdx(c), ...
            product.currentStartIdx(c), ...
            product.paymentIdx(c), ...
            mean(stats.couponPayoff(:, c)), ...
            stats.meanDiscountToPayment(c), ...
            stats.contribution(c), ...
            stats.discountError(c));

    end

    fprintf('------------------------------------------------------------\n');
    fprintf('Sum contribution       : %.12f EUR\n', sum(stats.contribution));
    fprintf('Max abs disc error     : %.12e\n', max(abs(stats.discountError)));
    fprintf('============================================================\n\n');

end