function report = printCalibrationReport(dates, discounts, surface, volsModel, modelType)
%PRINTCALIBRATIONREPORT Print calibration diagnostics for LMM or BMM vols.
%
%   report = printCalibrationReport(dates, discounts, surface, volsModel, modelType)
%
%   compares quoted cap prices implied by the flat volatility surface with
%   cap prices reconstructed from stripped caplet volatilities.
%
%   The first caplet fixing at the reference date is excluded from the
%   calibrated volatility matrix. Therefore:
%
%       size(volsModel,1) = numel(dates) - 2
%
%   Full caplet indexing convention:
%
%       caplet 1: dates(1) -> dates(2), already fixed at t0
%       caplet 2: dates(2) -> dates(3), first stochastic caplet
%
%   Therefore:
%
%       volsModel(i,:) corresponds to full caplet index i+1.
%
%   If modelType is 'LMM', the report compares:
%
%       target prices from LMM/Black caplet formula
%       reconstructed prices from LMM/Black stripped vols
%
%   If modelType is 'BMM', the report compares both:
%
%       1. target and reconstructed prices using the BMM caplet formula;
%       2. target and reconstructed prices using the LMM/Black caplet formula.
%
%   This is useful because BMM vols may be calibrated with BMM caplet prices,
%   but one may also want to check the price reconstruction under the usual
%   Black caplet formula.

    if nargin < 5 || isempty(modelType)
        modelType = 'LMM';
    end

    modelType = upper(string(modelType));

    if modelType ~= "LMM" && modelType ~= "BMM"
        error('modelType must be either ''LMM'' or ''BMM''.');
    end

    refDate = dates(1);

    strikes = surface.strikes(:).';
    maturities = surface.maturities(:).';
    flatVols = surface.vols;

    numberOfStrikes = numel(strikes);
    numberOfMaturities = numel(maturities);

    numberOfVolRows = size(volsModel, 1);
    expectedRows = numel(dates) - 2;

    if numberOfVolRows ~= expectedRows
        error(['volsModel must have %d rows because the first fixed caplet is excluded. ', ...
               'Received %d rows.'], expectedRows, numberOfVolRows);
    end

    delta = yearfrac( ...
        dates(1:end-1), ...
        dates(2:end), ...
        2);

    resetTimes = yearfrac( ...
        refDate, ...
        dates(1:end-1), ...
        3);

    forwardRates = ...
        (discounts(1:end-1) ./ discounts(2:end) - 1.0) ./ delta;

    dateTimes = yearfrac( ...
        refDate, ...
        dates, ...
        3);

    [~, maturityDateIdx] = min( ...
        abs(dateTimes(:) - maturities(:).'), ...
        [], ...
        1);

    if modelType == "LMM"

        report = buildSingleCalibrationReport( ...
            "LMM", ...
            @computeCapletPriceBlack, ...
            dates, ...
            discounts, ...
            surface, ...
            volsModel, ...
            strikes, ...
            flatVols, ...
            forwardRates, ...
            delta, ...
            resetTimes, ...
            maturityDateIdx);

        printSingleCalibrationReport(report);

    else

        reportBmm = buildSingleCalibrationReport( ...
            "BMM", ...
            @computeBmmCapletPrice, ...
            dates, ...
            discounts, ...
            surface, ...
            volsModel, ...
            strikes, ...
            flatVols, ...
            forwardRates, ...
            delta, ...
            resetTimes, ...
            maturityDateIdx);

        reportLmm = buildSingleCalibrationReport( ...
            "BMM vols repriced with LMM", ...
            @computeCapletPriceBlack, ...
            dates, ...
            discounts, ...
            surface, ...
            volsModel, ...
            strikes, ...
            flatVols, ...
            forwardRates, ...
            delta, ...
            resetTimes, ...
            maturityDateIdx);

        report = struct();

        report.modelType = 'BMM';
        report.bmm = reportBmm;
        report.lmmReprice = reportLmm;

        % Compatibility fields: default to the native BMM calibration report.
        report.marketPrices = reportBmm.marketPrices;
        report.modelPrices = reportBmm.modelPrices;
        report.absErrors = reportBmm.absErrors;
        report.relErrors = reportBmm.relErrors;
        report.maxAbsError = reportBmm.maxAbsError;
        report.maxRelError = reportBmm.maxRelError;
        report.rmse = reportBmm.rmse;

        printSingleCalibrationReport(reportBmm);
        printSingleCalibrationReport(reportLmm);

        fprintf('\n');
        fprintf('============================================================\n');
        fprintf('BMM Calibration Cross-Check Summary\n');
        fprintf('============================================================\n');
        fprintf('%28s %15s %15s %15s\n', ...
            'Pricing formula', 'MaxAbsError', 'MaxRelError', 'RMSE');
        fprintf('%28s %15s %15s %15s\n', ...
            '----------------------------', '---------------', '---------------', '---------------');
        fprintf('%28s %15.6e %15.6e %15.6e\n', ...
            'BMM', ...
            reportBmm.maxAbsError, ...
            reportBmm.maxRelError, ...
            reportBmm.rmse);
        fprintf('%28s %15.6e %15.6e %15.6e\n', ...
            'LMM reprice', ...
            reportLmm.maxAbsError, ...
            reportLmm.maxRelError, ...
            reportLmm.rmse);
        fprintf('============================================================\n\n');

    end

end