function [shock2yTable, shock6yTable, shock10yTable] = buildCoarseShocksTable( ...
    pillarDates, refDate)
%BUILDCOARSESHOCKSTABLE Build coarse-grained bucket shock timetables.
%
%   [shock2yTable, shock6yTable, shock10yTable] = ...
%       buildCoarseShocksTable(pillarDates, refDate)
%
%   builds three piecewise-linear shock profiles on the bootstrap pillar
%   dates. The interpolation variable is the ACT/365 year fraction from
%   refDate to each pillar date.
%
%   The output shocks are expressed directly in absolute rate units:
%
%       1 bp = 1.0e-4
%
%   Shock profiles:
%
%       0y-2y bucket:
%           +1 bp up to 2y, then linearly decreasing to 0 at 6y.
%
%       2y-6y bucket:
%           0 at 2y, +1 bp at 6y, then linearly decreasing to 0 at 10y.
%
%       6y-10y bucket:
%           0 up to 6y, linearly increasing to +1 bp at 10y, then flat
%           at +1 bp beyond 10y.
%
%   INPUTS:
%       pillarDates
%           Datetime vector containing the bootstrap pillar dates.
%
%       refDate
%           Market reference date.
%
%   OUTPUTS:
%       shock2yTable
%           Timetable containing the 0y-2y bucket shock.
%
%       shock6yTable
%           Timetable containing the 2y-6y bucket shock.
%
%       shock10yTable
%           Timetable containing the 6y-10y bucket shock.

    oneBp = 1.0e-4;

    pillarDates = pillarDates(:);

    pillarTimes = yearfrac( ...
        refDate, ...
        pillarDates, ...
        3);

    shock2yValues = interp1( ...
        [2, 6], ...
        [oneBp, 0.0], ...
        pillarTimes, ...
        'linear', ...
        0.0);

    shock2yValues(pillarTimes <= 2) = oneBp;

    shock6yValues = interp1( ...
        [2, 6, 10], ...
        [0.0, oneBp, 0.0], ...
        pillarTimes, ...
        'linear', ...
        0.0);

    shock10yValues = interp1( ...
        [6, 10], ...
        [0.0, oneBp], ...
        pillarTimes, ...
        'linear', ...
        0.0);

    shock10yValues(pillarTimes >= 10) = oneBp;

    shock2yTable = timetable( ...
        pillarDates, ...
        shock2yValues(:), ...
        'VariableNames', {'Shock'});

    shock6yTable = timetable( ...
        pillarDates, ...
        shock6yValues(:), ...
        'VariableNames', {'Shock'});

    shock10yTable = timetable( ...
        pillarDates, ...
        shock10yValues(:), ...
        'VariableNames', {'Shock'});

end